all: iter list object field main 
	g++ -o out main.cpp -std=c++17 -g
iter: 
	g++ -c iter.cpp -std=c++17 -g
list: 
	g++ -c list.cpp -std=c++17 -g
object: 
	g++ -c object.cpp -std=c++17 -g
field: 
	g++ -c field.cpp -std=c++17 -g
main: 
	g++ -c main.cpp -std=c++17 -g
clean:
	rm -f *.o out
