link_all: main.o iter.o field.o object.o
	g++ main.o iter.o object.o crown.o field.o -o main
main.o: main.cpp field.o
	g++ -c main.cpp
field.o: object.o field.cpp field.h
	g++ -c field.cpp
object.o: object.cpp object.h iter.o crown.o
	g++ -c object.cpp
iter.o: iter.cpp iter.h
	g++ -c iter.cpp
crown.o: crown.cpp crown.h
	g++ -c crown.cpp