all: iter list object field main 
	g++ -o out main.cpp -std=c++17 -g
iter:
	g++ -c iter -std=c++17 -g
list:
	g++ -c list -std=c++17 -g
object:
	g++ -c object -std=c++17 -g
field: 
	g++ -c field -std=c++17 -g
main: 
	g++ -c main.cpp -std=c++17 -g
